// Define your messages
const messages = {
    allreadyHaveAccount: "Already have account, Please Login",
    emailAlreadyExists: 'The email address is already in use.',
    userRegistered: 'User registration successful.',
    internalServerError: 'An internal server error occurred.',
    accountNotFound: "Account not found. Please check your details.",
    invalidPassword: "Invalid password.",
    loginSuccess: 'Login successfully.',
    emailNotFound: 'Email address not found. Please enter a valid email.',
    passwordResetLinkSentSuccesfully: 'Password reset link sent to your email.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    dataNotFound: "Data not found",
    passwordChanged: "Password changed successfully",
    passwordNotChanged: "Password not changed",
    passwordsDoNotMatch: 'Passwords do not match.',
    dataFoundSuccessful: 'Data found successfully',
    freeDemoRegistered: 'Free demo registration successful.',
    freeDemoNotFound: "No users found for the free demo.",
    idRequire: "Id must be require",
    dataAddedSuccessfull: "Data Added Sucessfully",
    freeDemoNotFoundOnGivenId: "No user found for the given ID in the free demo.",
    scheduleAdded: 'Schedule added successfully.',
    serverRunning: 'Node app is running on the specified port',
    passwordResetLink: "Please click the link below to reset your password.",
    passwordResetSubject: "Password Reset Request",
    invalidLink: "Invalid link. Please request a new one.",
    pageNotFound: "404 Error, Page Not Found",
    errorToSendingEmail: "Error sending email",
    dbConnectionError: 'Error when connecting to db:',
    dbConnectionSuccess: 'Connected to MySQL Server!',
    dbConnectionClosing: 'Closing database connection',
    dbError: 'Database connection error:',
    protocolConnectionLost: 'Database connection was lost. Reconnecting...',
    NO_TOKEN_PROVIDED: 'Unauthorized: No token provided',
    INVALID_OR_MISSING_TOKEN: 'Unauthorized: Invalid or missing token',
    INVALID_TOKEN: 'Unauthorized: Invalid token',
    USER_NOT_FOUND: 'User Not Found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    BILLING_INFO_ADD: "Your billing information has been saved successfully.",
    verifiedMessage: "Please click below link to email verified.",
    forgotPassword:"Forgot Password",
    accountActivate: "Activate account",
    accountVerifiedLinkSent: "Account verified link sent successfully. Please check your email ",
    failedToUsersCreate: "Failed to create user. Please try again later",
    accountVerifiedCodeSent: "Your account verification code has been sent to your registered email address. Please check your inbox to proceed with the verification.",
    otpVerified: "Your OTP has been successfully verified.",
    invalidOtp: "Invalid OTP. Please try again.",
    forgotPasswordOtpSend: "Your OTP for resetting your password has been sent to your registered email. Please check your inbox to proceed.",
    passwordAndConfirmPasswordNotMatch: "Password and Confirm Password do not match",
    userDetailedFoundSuccessfully: "User details retrieved successfully.",
    profileUpdatedSuccessfully: "Profile updated successfully!",
    userBlockedSuccessfully: "User has been successfully blocked.",
    userUnBlockedSuccessfully: "The user has been unblocked successfully.",
    hasFollowingYou: "started following you!",
    hasFollowCheckProfile: "has followed you. Check their profile now!",
    notificationSentSuccessfull: 'The notification was successfully sent!',
    notificationSendFailed: "Notification delivery failed for one or more recipients",
    unableToSendNotification: "Unable to send the notification. Please try again later.",
    requestSentSucessfull: "Request sent successfully.",
    requestNotSent: "The request could not be sent. Please try again.",
    requestAcceptSuccessfully: "Request Accepted Successfully",
    requestDecalinedSuccessfully: "Request Declined Successfully",
    unFollowedToUsers: "You have unfollowed this user.",
    postFoundSuccessfull: "The post has been found successfully.",
    postNotFound: "No post found.",
    likePost: "You have liked this post successfully.",
    unLikePost: "You have unliked this post.",
    commentAdded: "Your comment has been added successfully.",
    commentDelete: "Your comment has been deleted successfully.",
    insertError: "Failed to insert data into the database. Please try again later.",
    followSuccess: "You have successfully followed the user.",
    postCreate: "Post created successfully.",
    postCreatedFailed: "Post creation failed. Please try again.",
    notificationFetchSuccessfully: "Notifications retrieved successfully.",
    notificationFailedToFetch: "No notifications found for this user.",
    accountDeleteSuccessfull: "Your account has been successfully deleted.",
    accountNotDelete: "There was an error, and your account was not deleted",
    commentsPostedSuccessfull: "Comment posted successfully.",
    likeOnComments: "You liked this comment.",
    removeLikeCommentsOnPost: "Comment unlike successful.",
    notification: "Notification ",
    giveawayAnnoucment: "Give Away Annoucment ",
    wrongToggleType: "Plz Provide Proper Toggle Type",
    deleteCommentsSuccessfully: "Comment removed successfully.",
    failedToCommentsDelete: "Failed to delete the comment. Please try again.",
    hasCommentedCheckPost: "left a comment on your post. Check it out now!",
    commentOnPosts: "commented on your post",
    likeOnPost: "liked your post",
    hasLikedCheckPost:"just liked your post. See what’s trending!"

};

// Export the messages
export default messages;
